package com.example.SharedSpaces;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SharedSpacesApplication {

	public static void main(String[] args) {
		SpringApplication.run(SharedSpacesApplication.class, args);
	}

}


//"clientId":"461418541066-5c9p2cf0d6d8qthhgh7n2tjrd28pf3t9.apps.googleusercontent.com",
//		"credential":"eyJhbGciOiJSUzI1NiIsImtpZCI6Ijg1YmE5MzEzZmQ3YTdkNGFmYTg0ODg0YWJjYzg0MDMwMDQzNjMxODAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJuYmYiOjE2ODY4NDMxMzUsImF1ZCI6IjQ2MTQxODU0MTA2Ni01YzlwMmNmMGQ2ZDhxdGhoZ2g3bjJ0anJkMjhwZjN0OS5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjExMDA5NzY0OTU4NjMzODQyNTY4NiIsImhkIjoiZW5nLnBkbi5hYy5sayIsImVtYWlsIjoiZTE5MTI5QGVuZy5wZG4uYWMubGsiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXpwIjoiNDYxNDE4NTQxMDY2LTVjOXAyY2YwZDZkOHF0aGhnaDduMnRqcmQyOHBmM3Q5LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwibmFtZSI6IksuSC4gR1VOQVdBUkRBTkEiLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUFjSFR0ZVJUNTRoNlVGXzQ0MzFtSFFmN3p1eDJBanhWT21OeTZxaTY3NUU9czk2LWMiLCJnaXZlbl9uYW1lIjoiSy5ILiIsImZhbWlseV9uYW1lIjoiR1VOQVdBUkRBTkEiLCJpYXQiOjE2ODY4NDM0MzUsImV4cCI6MTY4Njg0NzAzNSwianRpIjoiODQwNzFjNzZjNjA5NmFhNTdhZTNhMzE4NzdiNDE3NzUxNzgzZTNkZCJ9.ZlPHsX6qbCRxpjF70zmyqeac5dabaLTRMOORzvj8kEZrWmXgijoPXebQsnuqnCHZcrUV7WClotBy5BliOLW6BApeEEQzYB8J0JvLcY2faCfq-_qOTnNLuDBDCt3uS9-NcQsjU7OJjorMNvEWd82QBk1PIfBpZzuDDMuFqXZCBB8GffI6GU2Bo3oJnUlfl9Rf_ThZQq3u1E6EhWKXBpcJnt8hse9G80PEGpEZ6EX2ZLIiMwrnOXun-STbJFCx5R6UlMmYcO4muBGtqN2gNbzKyn-EVEysoEWvcbGI-IekcVnanoFDarY8VA6WnWIZSgpQhzNzSjXTvJuZqzEba-jhsQ",
//		"select_by"
//		:
//		"btn"
